### ISSUE TITLE
`import shim from ". /shim.mjs"` worked fine on cloudflare pages a couple weeks ago, now I get `TypeError: an.fetch is not a function`

### ISSUE THREAD

**Issue by Jhonfunk** [cloudflare/workers-rs#576]
```javascript
import shim from "./shim.mjs"

export async function onRequest(context) {
  var rsp;
  try {
     rsp = shim.fetch(context.request, context.env, context);
  }
  catch(e) {
    return new Response("err:"+ e )
  }
  return rsp;
}
```

This code used to work fine on cloudflare pages, now it gets `TypeError: An.fetch is not a function`

**Comment by kflansburg** [comment]
Which version of worker-build are you using? It sounds like Pages may not support the new WorkerEntrypoint interface introduced for RPC.

**Comment by Jhonfunk** [comment]
@kflansburg 

Thanks.

After changing the version of worker-build back to 0.1.0 everything is fine.

Hopefully maybe the new WorkerEntrypoint interface could have some compatibility with the current Cloudflare Pages.

**Comment by Jhonfunk** [comment]
I used this code as Cloudflare Pages Fucntions. works fine with worker-build@0.1.0 and worker@0.1.0

@kflansburg

**Comment by kflansburg** [comment]
> I'm using this code as Cloudflare Pages Fucntions and it works fine with worker-build@0.1.0 + worker-rs@0.1.0
> 
> @kflansburg

Yes, what I'm saying is that the bug may not be with Pages, but with the JavaScript you posted in your first message. Where did that come from?

**Comment by Jhonfunk** [comment]
You can compile the hello-world template to get index.wasm and shim.mjs  then test it as Pages Functions using the code in myfirst message. 

@kflansburg

**Comment by kflansburg** [comment]
Yes, but where did the code in your first message come from? Is that your code? If so, you should update it to be compatible with the new interface.

**Comment by Jhonfunk** [comment]
@kflansburg

> After changing the version of worker-build back to 0.1.0 everything is fine.

Sorry, I wrote the wrong version number in this sentence. I actually switched back to version 0.0.10

You can compile the hello-world template to get index.wasm and shim.mjs  then test it as Pages Functions using the code in myfirst message.  

The problem occurs when you use worker-build@1.0.0 & worker-rs@0.2.0

**Comment by moixllik** [comment]
```toml
# Cargo.toml

worker = { version = "0.2.0" }
worker-macros = { version = "0.2.0" }
```

```js
// ./functions/_middleware.js

import * as shim from "./shim.mjs"
```

**Comment by Jhonfunk** [comment]
> ```toml
> # Cargo.toml
> 
> worker = { version = "0.2.0" }
> worker-macros = { version = "0.2.0" }
> ```
> 
> ```js
> // ./functions/_middleware.js
> 
> import * as shim from "./shim.mjs"
> ```

Thanks bro
