### ISSUE TITLE
[BUG] After upgrade from 0.0.17 to 0.0.18 wasm32-unknown-unknown build fails

### ISSUE THREAD

**Issue by JorritSalverda** [cloudflare/workers-rs#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.18

### What version of `wrangler` are you using?

3.5.0

### Describe the bug

After upgrading from version `0.0.17` to `0.0.18` the command `cargo build --target=wasm32-unknown-unknown` fails with errors like the following:

```
error[E0432]: unresolved import `crate::sys::IoSourceState`
  --> /Users/jorrit/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-0.8.8/src/io_source.rs:12:5
   |
12 | use crate::sys::IoSourceState;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `IoSourceState` in `sys`
```

The relevant part of the depency tree looks as follows:

```
└── worker v0.0.18
    ├── tokio v1.30.0
    │   ├── bytes v1.4.0
    │   ├── libc v0.2.147
    │   ├── mio v0.8.8
    │   │   └── libc v0.2.147
    │   ├── pin-project-lite v0.2.12
    │   └── socket2 v0.5.3
    │       └── libc v0.2.147
```

Before the upgrade tokio wasn't part of the run time dependencies. I wouldn't expect it to be since it doesn't run on Cloudflare Workers yet, right?

### Steps To Reproduce

I have trouble replicating the error in a fresh project but you can at least see the dependency tree go wrong by

1. On MacOs - or perhaps any other OS - create a new Rust project with `cargo init --lib`
2. Add the worker as dependency with `cargo add worker@0.0.18 --features queue`
3. Install the following other dependencies:

```
cargo add tokio-test@0.4.2 --dev
cargo add reqwest@0.11.18 --dev
```

4. Update `lib.rs` to the following content: 

```
use worker::*;

#[event(fetch)]
pub async fn main(_req: Request, _env: Env, _ctx: worker::Context) -> Result<Response> {
    Response::from_json(&true)
}

#[cfg(test)]
mod tests {
    #[test]
    fn ensure_tokio_test_is_used() {
        tokio_test::block_on(reqwest::get("https://httpbin.org/ip")).unwrap();
    }
}
```

5. Run `cargo tree`

Because the dev dependency includes tokio with features enabled the tree shows as

```
└── worker v0.0.18
    ├── tokio v1.30.0
    │   ├── bytes v1.4.0
    │   ├── libc v0.2.147
    │   ├── mio v0.8.8
    │   │   └── libc v0.2.147
    │   ├── pin-project-lite v0.2.12
    │   └── socket2 v0.5.3
    │       └── libc v0.2.147
```

instead of just

```
└── worker v0.0.18
    └── tokio v1.30.0
        └── pin-project-lite v0.2.12
```

In my library project this inclusion of `mio` actually causes the build error.

**Comment by JorritSalverda** [comment]
I've figured out that this is caused by the cargo resolver version 1 - the default - that doesn't distinguish between features for the same dependency between build dependencies and dev dependencies. Forcing Cargo to use resolver version 2 fixes this, see https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2.
