### ISSUE TITLE
[BUG] cargo install -q worker-build Don't work

### ISSUE THREAD

**Issue by remotejob** [cloudflare/workers-rs#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of `workers-rs` are you using?

0.0.9,  0.0.10,  0.0.11

### Describe the bug

Running custom build: cargo install -q worker-build && worker-build --release
error[E0658]: use of unstable library feature 'bool_to_option'
  --> /home/juno/.cargo/registry/src/github.com-1ecc6299db9ec823/worker-build-0.0.7/src/install.rs:14:14
   |
14 |             .then_some(path)
   |              ^^^^^^^^^
   |
   = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

### Steps To Reproduce

rustc 1.63.0
cargo 1.63.0
wrangler 2.0.28

cargo install -q worker-build 
error: could not compile `worker-build` due to previous error

**Comment by andogq** [comment]
Hi,

Was there a fix for this at all? I'm getting the same error when running `wrangler dev` (v2.0.28), `miniflare` (v2.7.1) and `cargo install -q worker-build` (tries installing 0.0.7).

Thanks!

**Comment by zebp** [comment]
> Hi,
> 
> Was there a fix for this at all? I'm getting the same error when running `wrangler dev` (v2.0.28), `miniflare` (v2.7.1) and `cargo install -q worker-build` (tries installing 0.0.7).
> 
> Thanks!

I'm not sure what @remotejob did to fix this issue as they were already on the latest Rust, but this should compile on any Rust >=1.62. The command `rustup update` should fix this for you if you are managing your Rust toolchain with [rustup](https://rustup.rs/) otherwise you should see what's the latest version for your package manager of choice.

**Comment by andogq** [comment]
`rustup update` worked perfectly, thank you!
